# Generated by Django 4.0.1 on 2022-01-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(default='-', max_length=255, upload_to='authors')),
                ('biography', models.TextField()),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'authors',
                'ordering': ['id'],
            },
        ),
    ]
